name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: debian-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: AWS ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: service_a
          file: service_a/Dockerfile
          push: true
          tags: ${{ github.sha }}
