name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Cd to service_a
        run: cd service_a
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run service
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8080 --daemon true
      - name: Run tests
        run: |
          curl -X GET http://0.0.0.0:8080/ping
