name: Build & publish on push to main

on:
  workflow_dispatch:
    inputs:
      image:
        type: string

  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build-and-push-ecr.yml
    with:
      ecr-repository: service_a
      aws-region: ${{ vars.AWS_REGION }}
      # image-tag: ${{ github.ref_name }}-${{ github.run_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
